// ============================================================
// VERSIONS VIEWER — generated by build_version_archive.py
// ============================================================

const VERSIONS_DATA = [
  {
    "group": "current",
    "key": "current",
    "title": "Текущая версия",
    "version": "Current build",
    "date": "2026-04-27",
    "status": "LIVE",
    "emoji": "🟦",
    "note": "Актуальная сборка оптимизатора.",
    "url": "./USE_Optimizer_v6_built.html"
  },
  {
    "key": "stable-2026-03-03",
    "title": "Стабильная версия",
    "version": "stable-2026-03-03",
    "date": "2026-03-03",
    "status": "STABLE",
    "emoji": "🟢",
    "note": "Отмеченная стабильная версия.",
    "url": "./stable/2026-03-03/",
    "archive_url": "./2026-03-03/",
    "group": "special"
  },
  {
    "key": "stable-2026-03-07",
    "title": "Стабильная версия",
    "version": "stable-2026-03-07",
    "date": "2026-03-07",
    "status": "STABLE",
    "emoji": "🟢",
    "note": "Более поздняя стабильная версия марта.",
    "url": "./stable/2026-03-07/",
    "archive_url": "./2026-03-07/",
    "group": "special"
  },
  {
    "key": "v6.2.2-before-audit",
    "title": "Версия перед аудитом",
    "version": "v6.2.2-before-audit",
    "date": "2026-04-15",
    "status": "SNAPSHOT",
    "emoji": "🟠",
    "note": "Отдельный снимок перед аудитом.",
    "url": "./stable/v6.2.2-before-audit/",
    "archive_url": "./v6.2.2-before-audit/",
    "group": "special"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-26",
    "title": "Архив по датам",
    "version": "2026-04-26",
    "date": "2026-04-26",
    "status": "DAILY",
    "emoji": "📅",
    "note": "3d63ee6 • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-04-26/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-25",
    "title": "Архив по датам",
    "version": "2026-04-25",
    "date": "2026-04-25",
    "status": "DAILY",
    "emoji": "📅",
    "note": "d86d1fc • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-04-25/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-23",
    "title": "Архив по датам",
    "version": "2026-04-23",
    "date": "2026-04-23",
    "status": "DAILY",
    "emoji": "📅",
    "note": "a7b8f0e • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-04-23/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-19",
    "title": "Архив по датам",
    "version": "2026-04-19",
    "date": "2026-04-19",
    "status": "DAILY",
    "emoji": "📅",
    "note": "1363e7b • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-04-19/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-20",
    "title": "Архив по датам",
    "version": "2026-04-20",
    "date": "2026-04-20",
    "status": "DAILY",
    "emoji": "📅",
    "note": "72a9bd0 • Merge pull request #326 from xopromo/fixes/trading-logic",
    "url": "./stable/daily/2026-04-20/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-15",
    "title": "Архив по датам",
    "version": "2026-04-15",
    "date": "2026-04-15",
    "status": "DAILY",
    "emoji": "📅",
    "note": "d4b5ab8 • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-04-15/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-14",
    "title": "Архив по датам",
    "version": "2026-04-14",
    "date": "2026-04-14",
    "status": "DAILY",
    "emoji": "📅",
    "note": "c056e4e • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-04-14/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-13",
    "title": "Архив по датам",
    "version": "2026-04-13",
    "date": "2026-04-13",
    "status": "DAILY",
    "emoji": "📅",
    "note": "08ad9d5 • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-04-13/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-11",
    "title": "Архив по датам",
    "version": "2026-04-11",
    "date": "2026-04-11",
    "status": "DAILY",
    "emoji": "📅",
    "note": "7910027 • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-04-11/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-05",
    "title": "Архив по датам",
    "version": "2026-04-05",
    "date": "2026-04-05",
    "status": "DAILY",
    "emoji": "📅",
    "note": "4a65b64 • feat: добавить старую версию оптимизатора (9e91177)",
    "url": "./stable/daily/2026-04-05/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-02",
    "title": "Архив по датам",
    "version": "2026-04-02",
    "date": "2026-04-02",
    "status": "DAILY",
    "emoji": "📅",
    "note": "9e91177 • feat: Pine Script индикатор Flat Zone Detector",
    "url": "./stable/daily/2026-04-02/"
  },
  {
    "group": "daily",
    "key": "daily-2026-04-01",
    "title": "Архив по датам",
    "version": "2026-04-01",
    "date": "2026-04-01",
    "status": "DAILY",
    "emoji": "📅",
    "note": "61b6ffc • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-04-01/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-31",
    "title": "Архив по датам",
    "version": "2026-03-31",
    "date": "2026-03-31",
    "status": "DAILY",
    "emoji": "📅",
    "note": "13044cc • fix: close indicator trade immediately on intrabar TP/SL touch",
    "url": "./stable/daily/2026-03-31/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-30",
    "title": "Архив по датам",
    "version": "2026-03-30",
    "date": "2026-03-30",
    "status": "DAILY",
    "emoji": "📅",
    "note": "6c331f9 • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-03-30/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-29",
    "title": "Архив по датам",
    "version": "2026-03-29",
    "date": "2026-03-29",
    "status": "DAILY",
    "emoji": "📅",
    "note": "7d1dab3 • Fix canvas null check and improve OOS diagnostic with TV CSV comparison note",
    "url": "./stable/daily/2026-03-29/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-28",
    "title": "Архив по датам",
    "version": "2026-03-28",
    "date": "2026-03-28",
    "status": "DAILY",
    "emoji": "📅",
    "note": "8c1a258 • fix: graph shows ML-filtered equity (not unfiltered TV equity)",
    "url": "./stable/daily/2026-03-28/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-27",
    "title": "Архив по датам",
    "version": "2026-03-27",
    "date": "2026-03-27",
    "status": "DAILY",
    "emoji": "📅",
    "note": "420dcb9 • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-03-27/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-26",
    "title": "Архив по датам",
    "version": "2026-03-26",
    "date": "2026-03-26",
    "status": "DAILY",
    "emoji": "📅",
    "note": "ec85bd7 • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-03-26/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-25",
    "title": "Архив по датам",
    "version": "2026-03-25",
    "date": "2026-03-25",
    "status": "DAILY",
    "emoji": "📅",
    "note": "394aaf6 • fix(pine): clamp consecMax defval to minval=2 to avoid Pine Script error",
    "url": "./stable/daily/2026-03-25/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-24",
    "title": "Архив по датам",
    "version": "2026-03-24",
    "date": "2026-03-24",
    "status": "DAILY",
    "emoji": "📅",
    "note": "8aedf53 • fix(pine_export): MA всегда попадает в CSV-экспорт",
    "url": "./stable/daily/2026-03-24/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-23",
    "title": "Архив по датам",
    "version": "2026-03-23",
    "date": "2026-03-23",
    "status": "DAILY",
    "emoji": "📅",
    "note": "c9ee187 • build: auto-update bundle [skip ci]",
    "url": "./stable/daily/2026-03-23/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-22",
    "title": "Архив по датам",
    "version": "2026-03-22",
    "date": "2026-03-22",
    "status": "DAILY",
    "emoji": "📅",
    "note": "f307ea3 • fix: закрывать окно создания проекта после успешного создания",
    "url": "./stable/daily/2026-03-22/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-19",
    "title": "Архив по датам",
    "version": "2026-03-19",
    "date": "2026-03-19",
    "status": "DAILY",
    "emoji": "📅",
    "note": "f91f9ce • fix(struct): исправить пивот-сравнение и отображение параметров",
    "url": "./stable/daily/2026-03-19/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-21",
    "title": "Архив по датам",
    "version": "2026-03-21",
    "date": "2026-03-21",
    "status": "DAILY",
    "emoji": "📅",
    "note": "987934c • Merge pull request #67 from xopromo/claude/strategy-game-html-GuTCf",
    "url": "./stable/daily/2026-03-21/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-20",
    "title": "Архив по датам",
    "version": "2026-03-20",
    "date": "2026-03-20",
    "status": "DAILY",
    "emoji": "📅",
    "note": "4e5f296 • Merge pull request #58 from xopromo/claude/strategy-game-html-GuTCf",
    "url": "./stable/daily/2026-03-20/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-17",
    "title": "Архив по датам",
    "version": "2026-03-17",
    "date": "2026-03-17",
    "status": "DAILY",
    "emoji": "📅",
    "note": "77a266c • Merge pull request #53 from xopromo/claude/vk-sales-automation-6eirg",
    "url": "./stable/daily/2026-03-17/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-16",
    "title": "Архив по датам",
    "version": "2026-03-16",
    "date": "2026-03-16",
    "status": "DAILY",
    "emoji": "📅",
    "note": "7fca6ae • Merge pull request #43 from xopromo/claude/vk-sales-automation-6eirg",
    "url": "./stable/daily/2026-03-16/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-15",
    "title": "Архив по датам",
    "version": "2026-03-15",
    "date": "2026-03-15",
    "status": "DAILY",
    "emoji": "📅",
    "note": "2231916 • fix(pine): MA Touch — separate mat_val from filter MA, fix zone logic",
    "url": "./stable/daily/2026-03-15/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-14",
    "title": "Архив по датам",
    "version": "2026-03-14",
    "date": "2026-03-14",
    "status": "DAILY",
    "emoji": "📅",
    "note": "69a3b4f • fix(buildBtCfg): useMA now respects cfg.useMA flag instead of maP>0",
    "url": "./stable/daily/2026-03-14/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-13",
    "title": "Архив по датам",
    "version": "2026-03-13",
    "date": "2026-03-13",
    "status": "DAILY",
    "emoji": "📅",
    "note": "e46023f • fix: add useMacdFilter/useER to all _cfg objects + OOS diagnostics",
    "url": "./stable/daily/2026-03-13/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-12",
    "title": "Архив по датам",
    "version": "2026-03-12",
    "date": "2026-03-12",
    "status": "DAILY",
    "emoji": "📅",
    "note": "76569e5 • feat: Kalman filter integration — 3 new applications",
    "url": "./stable/daily/2026-03-12/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-11",
    "title": "Архив по датам",
    "version": "2026-03-11",
    "date": "2026-03-11",
    "status": "DAILY",
    "emoji": "📅",
    "note": "bf8259e • fix: multiply maP by htfRatio in backtest start offset",
    "url": "./stable/daily/2026-03-11/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-10",
    "title": "Архив по датам",
    "version": "2026-03-10",
    "date": "2026-03-10",
    "status": "DAILY",
    "emoji": "📅",
    "note": "ab64ba1 • Fix MC/TPE/BO crash: пустой rsiPairs + try/catch + early yield",
    "url": "./stable/daily/2026-03-10/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-09",
    "title": "Архив по датам",
    "version": "2026-03-09",
    "date": "2026-03-09",
    "status": "DAILY",
    "emoji": "📅",
    "note": "9708364 • fix: create missing synthesis.js, pareto_front.js, synthesis_ui.js files and update build pipeline",
    "url": "./stable/daily/2026-03-09/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-08",
    "title": "Архив по датам",
    "version": "2026-03-08",
    "date": "2026-03-08",
    "status": "DAILY",
    "emoji": "📅",
    "note": "6c2244b • feat: table filter templates, panel collapse/grid, JS tooltip, global notepad",
    "url": "./stable/daily/2026-03-08/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-07",
    "title": "Архив по датам",
    "version": "2026-03-07",
    "date": "2026-03-07",
    "status": "DAILY",
    "emoji": "📅",
    "note": "6d9aeed • fix(pine_export): fix invalid timeframe format in f_tf_str",
    "url": "./stable/daily/2026-03-07/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-06",
    "title": "Архив по датам",
    "version": "2026-03-06",
    "date": "2026-03-06",
    "status": "DAILY",
    "emoji": "📅",
    "note": "a883d41 • Fix SL Pivot + new entry ranges: exhaustive loop, buildName, showDetail",
    "url": "./stable/daily/2026-03-06/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-04",
    "title": "Архив по датам",
    "version": "2026-03-04",
    "date": "2026-03-04",
    "status": "DAILY",
    "emoji": "📅",
    "note": "578740a • feat: add tlPvL/tlPvR as optimization dimensions for TL Touch/Break",
    "url": "./stable/daily/2026-03-04/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-03",
    "title": "Архив по датам",
    "version": "2026-03-03",
    "date": "2026-03-03",
    "status": "DAILY",
    "emoji": "📅",
    "note": "7bbd251 • chore: update STATE.md",
    "url": "./stable/daily/2026-03-03/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-02",
    "title": "Архив по датам",
    "version": "2026-03-02",
    "date": "2026-03-02",
    "status": "DAILY",
    "emoji": "📅",
    "note": "50871b2 • fix: compute bbD in _calcIndicators, log exceptions in _runOOS, diagnose IS>TV trades",
    "url": "./stable/daily/2026-03-02/"
  },
  {
    "group": "daily",
    "key": "daily-2026-03-01",
    "title": "Архив по датам",
    "version": "2026-03-01",
    "date": "2026-03-01",
    "status": "DAILY",
    "emoji": "📅",
    "note": "271046c • Fix runOOSScan: walk/param/noise/mc tests always returning 0",
    "url": "./stable/daily/2026-03-01/"
  },
  {
    "group": "daily",
    "key": "daily-2026-02-28",
    "title": "Архив по датам",
    "version": "2026-02-28",
    "date": "2026-02-28",
    "status": "DAILY",
    "emoji": "📅",
    "note": "432378e • fix: replace Groq API with claude CLI in research agent",
    "url": "./stable/daily/2026-02-28/"
  },
  {
    "group": "daily",
    "key": "daily-2026-02-27",
    "title": "Архив по датам",
    "version": "2026-02-27",
    "date": "2026-02-27",
    "status": "DAILY",
    "emoji": "📅",
    "note": "d42ba88 • fix(chart): restore sticky equity chart at top of viewport",
    "url": "./stable/daily/2026-02-27/"
  },
  {
    "group": "daily",
    "key": "daily-2026-02-26",
    "title": "Архив по датам",
    "version": "2026-02-26",
    "date": "2026-02-26",
    "status": "DAILY",
    "emoji": "📅",
    "note": "c77292f • fix(oos): prevent near-zero IS gain from inflating retention to thousands%",
    "url": "./stable/daily/2026-02-26/"
  }
];
const VERSION_GROUPS = [["current", "Текущая версия"], ["special", "Специальные версии"], ["daily", "Архив по датам"]];

function openVersionsModal() {
  _ensureVersionsModal();
  const overlay = document.getElementById('versions-modal-overlay');
  if (!overlay) return;
  overlay.style.display = 'flex';
  _renderVersionsList();
}

function closeVersionsModal() {
  const overlay = document.getElementById('versions-modal-overlay');
  if (overlay) overlay.style.display = 'none';
}

function _renderVersionsList() {
  const list = document.getElementById('versions-list');
  if (!list) return;
  const parts = [];
  VERSION_GROUPS.forEach(([groupKey, groupTitle]) => {
    const rows = VERSIONS_DATA.filter(v => v.group === groupKey);
    if (!rows.length) return;
    parts.push(`
      <div style="padding:14px 20px;border-bottom:1px solid var(--border);background:var(--bg3);position:sticky;top:0;z-index:1">
        <strong style="color:var(--accent)">${groupTitle}</strong>
        <span style="color:var(--text3);font-size:.82em;margin-left:8px">${rows.length}</span>
      </div>
    `);
    rows.forEach(v => {
      parts.push(`
        <div style="border-bottom:1px solid var(--border);padding:16px 20px;display:flex;gap:14px;align-items:flex-start;justify-content:space-between;flex-wrap:wrap">
          <div style="display:flex;gap:12px;align-items:flex-start;min-width:280px;flex:1">
            <div style="font-size:1.2em;line-height:1.2">${v.emoji}</div>
            <div>
              <div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:6px">
                <strong style="color:var(--accent)">${v.version}</strong>
                <span style="color:var(--text3);font-size:.8em">${v.date}</span>
                <span style="color:var(--text3);font-size:.75em;background:var(--bg3);padding:2px 8px;border-radius:3px">${v.status}</span>
              </div>
              <div style="color:var(--text);font-size:.92em;margin-bottom:4px">${v.title}</div>
              <div style="color:var(--text2);font-size:.84em">${v.note}</div>
            </div>
          </div>
          <div style="display:flex;gap:8px;align-items:center">
            <a href="${v.url}" target="_blank" rel="noopener noreferrer"
               style="padding:8px 12px;background:rgba(0,212,255,.15);border:1px solid var(--accent);border-radius:6px;color:var(--accent);font-size:.85em;text-decoration:none;white-space:nowrap">
              Открыть версию
            </a>
          </div>
        </div>
      `);
    });
  });
  list.innerHTML = parts.join('');
}

function _ensureVersionsModal() {
  if (document.getElementById('versions-modal-overlay')) return;
  const wrap = document.createElement('div');
  wrap.innerHTML = `
    <div id="versions-modal-overlay" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.85);z-index:9999;align-items:center;justify-content:center;padding:24px" onclick="if(event.target===this)closeVersionsModal()">
      <div style="background:var(--bg);border:1px solid var(--border);border-radius:8px;width:100%;max-width:980px;max-height:85vh;display:flex;flex-direction:column;overflow:hidden">
        <div style="padding:16px 20px;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;align-items:center">
          <div style="display:flex;align-items:center;gap:12px">
            <span style="font-size:1.4em">🗂</span>
            <div>
              <h2 style="margin:0;color:var(--accent)">Версии</h2>
              <div style="font-size:.8em;color:var(--text3)">Отдельные страницы по датам: специальные снимки и полный архив за последние месяцы.</div>
            </div>
          </div>
          <button onclick="closeVersionsModal()" style="background:none;border:none;color:var(--text3);cursor:pointer;font-size:1.3em">✕</button>
        </div>
        <div style="padding:12px 20px;background:var(--bg3);border-bottom:1px solid var(--border);font-size:.85em;color:var(--text2)">
          У каждой версии видны подпись, дата и тип. Открытие идет на отдельной надежной странице.
        </div>
        <div id="versions-list" style="flex:1;overflow-y:auto;padding:0">
          <div style="padding:20px;text-align:center;color:var(--text3)">Загрузка...</div>
        </div>
      </div>
    </div>
  `;
  document.body.appendChild(wrap.firstElementChild);
}

try { window.openVersionsModal = openVersionsModal; } catch(e) {}
try { window.closeVersionsModal = closeVersionsModal; } catch(e) {}
